# Generated by Django 4.2.4 on 2023-11-21 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='full_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
