# Generated by Django 4.2.10 on 2024-02-26 12:03

import WorldOfSpeedApp.profiles.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[WorldOfSpeedApp.profiles.custom_validators.custom_minlength_validator, WorldOfSpeedApp.profiles.custom_validators.user_name_validator]),
        ),
    ]
