# Generated by Django 4.2.4 on 2023-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(),
        ),
    ]
