# Generated by Django 4.2.10 on 2024-02-26 12:03

import WorldOfSpeedApp.cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_username'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=WorldOfSpeedApp.cars.models.UniqueURLField(default='https://...', error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
        ),
    ]
